# Generated by Django 4.0.3 on 2022-04-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-date_of_entry'],
            },
        ),
    ]
